name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create pull request for ${{ github.event.client_payload.ReleaseBranchName }}
        id: create-pr
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let response = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "${{ github.event.client_payload.PullRequestTitle }}",
              head: "${{ github.event.client_payload.ReleaseBranchName }}-docs",
              base: "${{ github.event.client_payload.PullRequestBase }}",
              body: `${{ github.event.client_payload.PullRequestBody }}`
            });
            console.log(response.data.html_url);
