name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  Create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        ref: 0213-fix-code-block

      - name: Create pull request
        id: create-pr
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let response = await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Test PR",
              head: "0213-fix-code-block",
              base: "master",
            });
            console.log(response.data.html_url);
